id = "hjson"
name = "HJSON"
description = "HJSON language support for Zed (syntax highlighting and formatting)."
version = "1.0.0"
schema_version = 1
authors = ["Gardamuse <gardamuse@blushingdefeat.com>"]
repository = "https://github.com/zed-extensions/hjson"

[grammars.hjson]
repository = "https://github.com/Gardamuse/hjson-tree-sitter"
rev = "78af1b721db4c090cceef7f8f8b8f83faf2cab92"

[language_servers.hjson-language-server]
name = "HJSON Formatter"
languages = ["HJSON"]

